### ISSUE TITLE
use pipx ?

### ISSUE THREAD

**Issue by stevieflow** [davidmegginson/iatisplit#4]
Hi @davidmegginson 

Thanks, as always, for this repo!

I just tried to install on a new laptop, with python 3.12.3 with

> pip3 install iatisplit

and got:

```

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

```

I got around it by installing pipx and all is fine

Not sure if this is a me issue, or something to tweak in the README?

Thanks

**Comment by davidmegginson** [comment]
Thanks for the report.  That's Debian warning you that you're trying to install the package globally instead of in a virtual environment (which Debian appears not to like).  The same issue, presumably, applies to any Python package you want to install from PyPi, but let me know if this one is behaving differently.
